include:
 - exemple/blocks/gallery/__item
 - exempleblocks/page/__comments
 - exemple/blocks/page/__cover
 - exemple/blocks/page/__footer
 - exemple/blocks/page/__gallery
 - exemple/blocks/page/__header
 - exemple/blocks/page/__intro
 - exemple/blocks/page/__lead
 - exemple/blocks/page/__places
 - exemple/blocks/page/__vedeo

