include:
- blocks/places/__description
- blocks/places/__description-text
- blocks/places/__link
- blocks/places/__place-item
- blocks/places/__place-item-titile
- blocks/places/__theme-photo
- blocks/places/__url
- blocks/places/__lead
- blocks/places/__wrapper-link
- blocks/places/__vedeo
- blocks/page/__header
- blocks/page/__gallery
- blocks/page/__lead
- blocks/page/__comments
- blocks/page/__video
- blocks/page/__footer
- blocks/header/__language
- blocks/header/__languages