include:
- /blocks/places/__item
- /blocks/places/__comments
- /blocks/places/__cover
- /blocks/places/__footer
- /blocks/places/__gallery
- /blocks/places/__header
- /blocks/places/__intro
- /blocks/places/__lead
- /blocks/places/__places
- /blocks/places/__vedeo